name: C/C++ CI

on: [pull_request,workflow_dispatch]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: Dependencies
      run: >
       sudo apt-get install build-essential libboost-dev libboost-all-dev libssl-dev
       libdb++-dev libminiupnpc-dev libleveldb-dev -y
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: QMake
      run: qmake RELEASE=1
    - name: Make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: litedoge-qt
        path: litedoge-qt