name: C/C++ CI

on: [pull_request,workflow_dispatch]

jobs:
  ubuntu-build:
    strategy:
      matrix:
        qt-version: [5.12.8, 5.15.2]
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
    - name: Dependencies
      run: >
       sudo apt-get install build-essential libboost-dev libboost-all-dev libssl-dev
       libdb++-dev libminiupnpc-dev libleveldb-dev -y
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: QMake
      run: qmake RELEASE=1
    - name: Make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: litedoge-qt
        path: litedoge-qt